language: elixir
elixir:
  - 1.7.4
  - 1.8.2
  - 1.9.4

env:
  - MIX_ENV=test

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix deps.compile

script:
  - mix coveralls.travis

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
